version: '3'

vars:
  GKE_WEST_DIR: ../clusters/gke-europe-west1/terraform
  GKE_SW_DIR: ../clusters/gke-southwest/terraform
  DC1_DIR: ../clusters/dc1/terraform
  ADMIN_PARTITIONS_DIR: ../consul/admin-partitions

tasks:
  help:
    desc: "Show admin partitions setup guide"
    cmds:
      - echo "🏢 === CONSUL ADMIN PARTITIONS ==="
      - echo ""
      - echo "Multi-tenant isolation within Consul datacenter using GKE clusters"
      - echo ""
      - echo "📋 PREREQUISITES -"
      - echo "  ✅ DC1 cluster deployed (Consul servers)"
      - echo "  ✅ Consul Enterprise license configured"
      - echo "  ✅ GKE clusters deployed"
      - echo ""
      - echo "📖 DOCUMENTATION - consul/admin-partitions/README.md"
      - echo ""
      - echo "🚀 SETUP TASKS -"
      - echo "  deploy-gke      - Deploy both GKE clusters"
      - echo "  setup-acls      - Create ACL policies and roles"
      - echo "  create-partitions - Create admin partitions"
      - echo "  setup-secrets   - Configure Kubernetes secrets"
      - echo "  deploy-consul   - Deploy Consul on GKE clusters"
      - echo "  complete        - Full automated setup"
      - echo ""
      - echo "🔧 APPLICATION TASKS -"
      - echo "  deploy-boutique - Deploy Google Boutique demo app"
      - echo "  create-intentions - Configure service intentions"
      - echo "  status-boutique - Check boutique app status"
      - echo ""
      - echo "🗑️  CLEANUP -"
      - echo "  cleanup         - Remove admin partitions configuration"
      - echo ""
      - echo "📖 QUICK START -"
      - echo "  task -t tasks/admin-partitions.yml complete"

  deploy-gke:
    desc: "Deploy both GKE clusters for admin partitions"
    cmds:
      - echo "🚀 Deploying GKE clusters for admin partitions..."
      - task: ../Taskfile.yml:deploy-both-gke
      - echo "✅ GKE clusters ready for admin partitions"

  setup-acls:
    desc: "Create ACL policies and roles for admin partitions"
    cmds:
      - echo "🔐 Setting up ACL policies and roles..."
      - echo "This step requires manual execution on Consul servers"
      - echo ""
      - echo "See - consul/admin-partitions/README.md - Phase 2"
      - echo ""
      - echo "1. SSH to DC1 server - task ssh-dc1-server"
      - echo "2. Create partition policies for k8s-west1 and k8s-southwest1"
      - echo "3. Create ACL roles for different environments"

  create-partitions:
    desc: "Create admin partitions on Consul servers"
    cmds:
      - echo "🏢 Creating admin partitions..."
      - echo "This step requires manual execution on Consul servers"
      - echo ""
      - echo "See - consul/admin-partitions/README.md - Phase 3"
      - echo ""
      - echo "1. SSH to DC1 server - task ssh-dc1-server"
      - echo "2. Create k8s-west1 partition"
      - echo "3. Create k8s-southwest1 partition"
      - echo "4. Create partition tokens"

  setup-secrets:
    desc: "Setup Kubernetes secrets for Consul integration"
    cmds:
      - echo "🔑 Setting up Kubernetes secrets..."
      - echo "This step requires manual execution with kubectl"
      - echo ""
      - echo "See - consul/admin-partitions/README.md - Phase 4"
      - echo ""
      - echo "1. Authenticate with both GKE clusters"
      - echo "2. Create consul namespace"
      - echo "3. Create enterprise license secret"
      - echo "4. Create partition tokens"
      - echo "5. Create CA certificates"

  deploy-consul:
    desc: "Deploy Consul on GKE clusters with admin partitions"
    cmds:
      - echo "🔗 Deploying Consul on GKE clusters..."
      - echo "This step requires manual execution with Helm"
      - echo ""
      - echo "See - consul/admin-partitions/README.md - Phase 4.3"
      - echo ""
      - echo "1. Switch to each GKE cluster context"
      - echo "2. Setup Helm values for each partition"
      - echo "3. Deploy Consul using Helm"
      - echo "4. Verify deployment"

  deploy-boutique:
    desc: "Deploy Google Boutique microservices demo"
    cmds:
      - echo "🛍️  Deploying Google Boutique demo application..."
      - echo "This demonstrates cross-partition service mesh"
      - echo ""
      - echo "See - consul/admin-partitions/README.md - Boutique Application section"
      - echo ""
      - echo "1. Deploy to k8s-southwest1 partition"
      - echo "2. Configure service intentions"
      - echo "3. Test application functionality"

  create-intentions:
    desc: "Create service intentions for boutique app"
    cmds:
      - echo "🔒 Creating service intentions..."
      - echo "Required for service-to-service communication in Enterprise"
      - echo ""
      - echo "consul intention create -allow frontend.development.k8s-southwest1 currencyservice.development.k8s-southwest1"
      - echo "consul intention create -allow frontend.development.k8s-southwest1 productcatalogservice.development.k8s-southwest1"
      - echo "consul intention create -allow frontend.development.k8s-southwest1 cartservice.development.k8s-southwest1"
      - echo "consul intention create -allow cartservice.development.k8s-southwest1 redis-cart.development.k8s-southwest1"

  status-boutique:
    desc: "Check boutique application status"
    cmds:
      - echo "📊 Checking boutique application status..."
      - echo "Run these commands to check status -"
      - echo ""
      - echo "# Check pods"
      - echo "kubectl get pods -n development"
      - echo ""
      - echo "# Check services in Consul"
      - echo "consul catalog services -partition k8s-southwest1 -namespace development"
      - echo ""
      - echo "# Port forward to access frontend"
      - echo "kubectl port-forward svc/frontend 8080:80 -n development"

  complete:
    desc: "Complete admin partitions setup"
    cmds:
      - echo "🚀 Starting complete admin partitions setup..."
      - task: deploy-gke
      - echo ""
      - echo "⚠️  MANUAL STEPS REQUIRED -"
      - echo "The following steps require manual execution -"
      - echo ""
      - echo "1. Setup ACL policies and roles on Consul servers"
      - echo "2. Create admin partitions"
      - echo "3. Configure Kubernetes secrets"
      - echo "4. Deploy Consul on GKE clusters"
      - echo "5. Deploy demo applications"
      - echo ""
      - echo "📖 Follow the detailed guide - consul/admin-partitions/README.md"

  cleanup:
    desc: "Remove admin partitions configuration"
    cmds:
      - echo "🗑️  Cleaning up admin partitions..."
      - echo "This will remove partitions and associated resources"
      - echo ""
      - echo "1. Delete applications from GKE clusters"
      - echo "2. Remove Consul from GKE clusters"
      - echo "3. Delete admin partitions from Consul servers"
      - echo "4. Clean up ACL policies and roles"
      - echo ""
      - echo "⚠️  Use with caution - this removes all partition data"

  default:
    desc: "Show help by default"
    cmds:
      - task: help