# CTS Integration with Existing GKE Southwest Infrastructure
# This module integrates CTS with your existing GKE-southwest workspace
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    consul = {
      source  = "hashicorp/consul"
      version = "~> 2.0"
    }
  }
}

# Variable that CTS provides - services discovered from Consul
variable "services" {
  description = "Services monitored by CTS from Consul k8s-southwest1 partition"
  type        = map(object({
    id      = string
    name    = string
    address = string
    port    = number
    tags    = list(string)
  }))
}

# Reference your existing GKE cluster from the GKE-southwest workspace
data "google_container_cluster" "existing_cluster" {
  name     = "gke-southwest-gke"  # Based on your ${var.cluster_name}-gke pattern
  location = "europe-southwest1"  # Your GKE region
}

# Reference your existing network from the GKE-southwest workspace
data "google_compute_network" "existing_network" {
  name = "gke-southwest-gke-network"  # Based on your ${var.cluster_name}-gke-network pattern
}

# Create additional firewall rules for discovered services
resource "google_compute_firewall" "consul_services_ingress" {
  for_each = { for name, svc in var.services : name => svc if svc.name == "frontend" }
  
  name    = "cts-boutique-${replace(each.key, ".", "-")}-ingress"
  network = data.google_compute_network.existing_network.name

  allow {
    protocol = "tcp"
    ports    = [tostring(each.value.port)]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["gke-node"]
  description   = "CTS managed firewall rule for ${each.value.name} service"
}

# Create Consul KV entries to track CTS infrastructure changes
resource "consul_keys" "cts_infrastructure_state" {
  key {
    path  = "cts/gke-southwest/infrastructure/firewall_rules"
    value = jsonencode({
      timestamp = timestamp()
      rules_created = length([for s in var.services : s if s.name == "frontend"])
      service_ports = [for name, svc in var.services : "${svc.name}:${svc.port}"]
      cluster_name = data.google_container_cluster.existing_cluster.name
      network_name = data.google_compute_network.existing_network.name
    })
  }
  
  key {
    path  = "cts/gke-southwest/services/current_state"
    value = jsonencode({
      timestamp = timestamp()
      total_services = length(var.services)
      services = {
        for name, svc in var.services : name => {
          name = svc.name
          address = svc.address
          port = svc.port
          tags = svc.tags
        }
      }
      partition = "k8s-southwest1"
      namespace = "production"
    })
  }
}

# Create monitoring configuration for the boutique services
resource "local_file" "gke_service_monitoring" {
  filename = "/tmp/gke-southwest-services.json"
  content = jsonencode({
    timestamp = timestamp()
    cluster = data.google_container_cluster.existing_cluster.name
    location = data.google_container_cluster.existing_cluster.location
    network = data.google_compute_network.existing_network.name
    services = {
      for name, service in var.services : name => {
        name = service.name
        endpoint = "${service.address}:${service.port}"
        firewall_rule = service.name == "frontend" ? google_compute_firewall.consul_services_ingress[name].name : null
        monitoring_target = "${service.address}:${service.port}"
        health_check_url = "http://${service.address}:${service.port}/health"
      }
    }
    infrastructure_updates = {
      firewall_rules_created = length([for s in var.services : s if s.name == "frontend"])
      consul_kv_updated = true
    }
  })
}

# Generate Terraform configuration for HCP Terraform workspace integration
resource "local_file" "hcp_terraform_config" {
  filename = "/tmp/cts-generated-config.tf"
  content = <<-EOF
# Generated by CTS for HCP Terraform integration
# Copy this content to your GKE-southwest workspace for production deployment

terraform {
  cloud {
    organization = "pablogd-hcp-test"
    workspaces {
      name = "GKE-southwest"
    }
  }
}

# CTS-discovered services (${length(var.services)} services found)
locals {
  cts_services = ${jsonencode(var.services)}
  frontend_services = ${jsonencode([for name, svc in var.services : svc if svc.name == "frontend"])}
}

# Reference existing GKE cluster
data "google_container_cluster" "existing_cluster" {
  name     = "gke-southwest-gke"
  location = "europe-southwest1"
}

data "google_compute_network" "existing_network" {
  name = "gke-southwest-gke-network"
}

# CTS-managed firewall rules for discovered services
%{for name, svc in var.services~}
%{if svc.name == "frontend"~}
resource "google_compute_firewall" "cts_${replace(name, ".", "_")}_ingress" {
  name    = "cts-boutique-${replace(name, ".", "-")}-ingress"
  network = data.google_compute_network.existing_network.name

  allow {
    protocol = "tcp"
    ports    = ["${svc.port}"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags   = ["gke-node"]
  description   = "CTS managed: ${svc.name} service (${svc.address}:${svc.port})"
}
%{endif~}
%{endfor~}

# Output for monitoring
output "cts_integration_status" {
  value = {
    timestamp = "${timestamp()}"
    services_discovered = ${length(var.services)}
    firewall_rules_managed = ${length([for s in var.services : s if s.name == "frontend"])}
    cluster_integration = data.google_container_cluster.existing_cluster.name
  }
}
EOF
}

# Output integration summary
output "gke_integration_summary" {
  value = {
    timestamp = timestamp()
    cluster_integration = {
      cluster_name = data.google_container_cluster.existing_cluster.name
      cluster_location = data.google_container_cluster.existing_cluster.location
      network_name = data.google_compute_network.existing_network.name
      services_integrated = length(var.services)
    }
    infrastructure_updates = {
      firewall_rules = [
        for name, svc in var.services : 
        google_compute_firewall.consul_services_ingress[name].name 
        if svc.name == "frontend"
      ]
      monitoring_config = local_file.gke_service_monitoring.filename
      consul_kv_entries = [
        "cts/gke-southwest/infrastructure/firewall_rules",
        "cts/gke-southwest/services/current_state"
      ]
    }
    service_discovery = {
      partition = "k8s-southwest1"
      namespace = "production"
      services_monitored = [for name, svc in var.services : svc.name]
      frontend_services = [for name, svc in var.services : svc.name if svc.name == "frontend"]
    }
  }
}
