---
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
# ServiceAccounts for core services only
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cart
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: development
---
# Frontend Service + Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/partition: "k8s-southwest1"
        consul.hashicorp.com/namespace: "development"
        consul.hashicorp.com/connect-service-upstreams: "productcatalogservice.development.k8s-southwest1:3550,cartservice.development.k8s-southwest1:7070,currencyservice.development.k8s-southwest1:7000"
    spec:
      serviceAccountName: frontend
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "localhost:3550"
            - name: CART_SERVICE_ADDR
              value: "localhost:7070"
            # Disable other services by setting dummy addresses
            - name: CURRENCY_SERVICE_ADDR
              value: "localhost:7000"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "localhost:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "localhost:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "localhost:5050"
            - name: AD_SERVICE_ADDR
              value: "localhost:9555"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: development
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: frontend
---
# Product Catalog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/partition: "k8s-southwest1"
        consul.hashicorp.com/namespace: "development"
    spec:
      serviceAccountName: productcatalogservice
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: development
spec:
  ports:
    - port: 3550
      name: grpc
      targetPort: 3550
  selector:
    app: productcatalogservice
---
# Cart Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/partition: "k8s-southwest1"
        consul.hashicorp.com/namespace: "development"
        consul.hashicorp.com/connect-service-upstreams: "redis-cart.development.k8s-southwest1:6379"
    spec:
      serviceAccountName: cartservice
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
          ports:
            - containerPort: 7070
          env:
            - name: PORT
              value: "7070"
            - name: REDIS_ADDR
              value: "localhost:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: development
spec:
  ports:
    - port: 7070
      name: grpc
      targetPort: 7070
  selector:
    app: cartservice
---
# Redis Cart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/partition: "k8s-southwest1"
        consul.hashicorp.com/namespace: "development"
    spec:
      serviceAccountName: redis-cart
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: development
spec:
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
  selector:
    app: redis-cart
---
# Currency Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/partition: "k8s-southwest1"
        consul.hashicorp.com/namespace: "development"
    spec:
      serviceAccountName: currencyservice
      containers:
        - name: server
          image: gcr.io/google-samples/microservices-demo/currencyservice:v0.8.0
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: development
spec:
  ports:
    - port: 7000
      name: grpc
      targetPort: 7000
  selector:
    app: currencyservice