# Service Accounts for Boutique Microservices
# Each service needs its own service account to match Consul service names

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: development

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cart
  namespace: development