# This file is generated by Consul-Terraform-Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Consul-Terraform-Sync. Any manual changes to
# this file may not be preserved and could be overwritten by a subsequent
# update.
#
# Task: production-boutique-automation
# Description: Monitor production boutique services and generate automation

terraform {
  required_version = ">= 0.13.0, <= 1.7.5"
  backend "consul" {
    address = "http://34.88.51.53:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}


# Monitor production boutique services and generate automation
module "production-boutique-automation" {
  source   = "/Users/pablod/Documents/Infrastructure/nomad/02-consul-nomad-gcp/hashistack-gcp/consul/demo-all/simple-module"
  services = var.services
}
